### ISSUE TITLE
Unexpected exit of renderer process

### ISSUE THREAD

**Issue by YukariChiba** [AOSC-Dev/chromium-loongarch64#1]
## Environment

[deepin v23 on loong64](https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/) with [qt6-webengine](https://github.com/deepin-community/qt6-webengine/) 6.6.3, latest [patch](https://github.com/deepin-community/qt6-webengine/blob/master/debian/patches/loong64.patch) included.

## Reproduce

1. Install deepin v23.
2. Install `qt6-webengine-examples`
3. Run `/usr/lib/loongarch64-linux-gnu/qt6/examples/webenginewidgets/simplebrowser/simplebrowser`
4. An error would appear: `Render process exited with code:5`

**Comment by jiegec** [comment]
> ## Environment
> 
> [deepin v23 on loong64](https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/) with [qt6-webengine](https://github.com/deepin-community/qt6-webengine/) 6.6.3, latest [patch](https://github.com/deepin-community/qt6-webengine/blob/master/debian/patches/loong64.patch) included.
> ## Reproduce
> 
>     1. Install deepin v23.
> 
>     2. Install `qt6-webengine-examples`
> 
>     3. Run `/usr/lib/loongarch64-linux-gnu/qt6/examples/webenginewidgets/simplebrowser/simplebrowser`
> 
>     4. An error would appear: `Render process exited with code:5`

Thanks for reporting, I am trying to reproduce the problem.

**Comment by jiegec** [comment]
I have reproduced the bug:

```
(gdb) bt
#0  0x00007fffe65662f0 in v8::internal::Deserializer<v8::internal::Isolate>::Deserializer(v8::internal::Isolate*, v8::base::Vector<unsigned char const>, unsigned int, bool, bool) () from /lib/loongarch64-linux-gnu/libQt6WebEngineCore.so.6
#1  0x00007fffe656628c in v8::internal::Deserializer<v8::internal::Isolate>::Deserializer(v8::internal::Isolate*, v8::base::Vector<unsigned char const>, unsigned int, bool, bool) () from /lib/loongarch64-linux-gnu/libQt6WebEngineCore.so.6
Backtrace stopped: frame did not save the PC
```

**Comment by jiegec** [comment]
Seemed like some memory corruption... You can try updated patch from https://github.com/AOSC-Dev/chromium-loongarch64/commit/0e0582e586abffe83c0361ce2cae1401f406f2a0, but I am not sure if it is the problem.

**Comment by YukariChiba** [comment]
> Seemed like some memory corruption... You can try updated patch from [0e0582e](https://github.com/AOSC-Dev/chromium-loongarch64/commit/0e0582e586abffe83c0361ce2cae1401f406f2a0), but I am not sure if it is the problem.

Verified, NOT work.

**Comment by jiegec** [comment]
> > Seemed like some memory corruption... You can try updated patch from [0e0582e](https://github.com/AOSC-Dev/chromium-loongarch64/commit/0e0582e586abffe83c0361ce2cae1401f406f2a0), but I am not sure if it is the problem.
> 
> Verified, NOT work.

Then I have no idea.. And it is not reproducible on AOSC OS.

**Comment by MingcongBai** [comment]
Closing as invalid.
